import { useContext, useEffect, useState } from "react";
import { global } from "../assets/context";
import { layer } from "../Components/opsi";

export default function FormDetail() {
  const dataID = useContext(global).dataID;

  const [room, setRoom] = useState();
  useEffect(() => {
    fetch(`https://6507a74b3a38daf4803f9ee4.mockapi.io/api/v1/rooms/${dataID}`)
      .then((res) => res.json())
      .then(setRoom);
  }, [dataID]);

  const close = () => {
    layer(document.getElementById("layerFormDetail"));
  };

  return (
    room && (
      <div
        id="layerFormDetail"
        className="h-screen w-screen absolute z-30 top-0 left-0 justify-center hidden"
      >
        <div className="min-w-[500px] w-screen h-screen bg-primary-blue opacity-60" />
        <div
          className="
          font-raleway 
          px-4 
          min-[320px]:px-8
          py-12 
          bg-zinc-100 
          rounded-sm 
          h-fit 
          absolute 
          top-[20px]
          min-[768px]:top-[70px]
          w-fit
          min-[768px]:w-[500px]
          min-[1024px]:w-[800px]
          min-[1440px]:w-[900px]
          min-[1920px]:w-[1200px]
          "
        >
          <button
            onClick={close}
            className="absolute right-6 top-4 font-raleway text-zinc-700 hover:bg-zinc-200 py-1 px-3 rounded-full lg:text-2xl"
          >
            X
          </button>
          <div
            className="
          text-center font-bold
          lg:text-3xl"
          >
            Detail Kamar
          </div>
          <form
            className="
          text-sm 
          min-[425px]:text-[13px]
          min-[1024px]:text-lg
          min-[1440px]:text-xl
          min-[1920px]:text-2xl
          mt-4 overflow-auto font-raleway capitalize"
          >
            <div
              className="
            grid 
            grid-cols-2 
            w-[220px]
            min-[1024px]:w-[300px]
            min-[1920px]:w-[450px]
            "
            >
              <label
                className="
                font-semibold
                text-third-blue
                mb-2 
                w-[200px]"
              >
                Kategori Kamar
              </label>
              <span
                className="
                max-[424px]:text-[10px] 
                text-zinc-600 
                w-[150px]
                min-[768px]:w-[300px]
                min-[1024px]:w-[500px]
                min-[1440px]:w-[600px]"
              >
                {room.kategori}
              </span>
            </div>
            <div
              className="
              grid 
              grid-cols-2 
              w-[220px]
              min-[1024px]:w-[300px]
              min-[1920px]:w-[450px]
              "
            >
              <label
                className="
                font-semibold
                text-third-blue
                mb-2 
                w-[200px]"
              >
                Lantai Kamar
              </label>
              <span
                className="
                max-[424px]:text-[10px] 
              text-zinc-600 
              w-[150px]
              min-[768px]:w-[300px]
              min-[1024px]:w-[500px]
              min-[1440px]:w-[600px]"
              >
                {room.lantai}
              </span>
            </div>
            <div
              className="
              grid 
              grid-cols-2 
              w-[220px]
              min-[1024px]:w-[300px]
              min-[1920px]:w-[450px]
              "
            >
              <label
                className="
                font-semibold
                text-third-blue
                mb-2 
                w-[200px]"
              >
                Nomor Kamar
              </label>
              <span
                className="
                max-[424px]:text-[10px]
                text-zinc-600 
                w-[150px]
                min-[768px]:w-[300px]
                min-[1024px]:w-[500px]
                min-[1440px]:w-[600px]"
              >
                {room.nomorKamar}
              </span>
            </div>
            <div
              className="
              grid 
              grid-cols-2 
              w-[220px]
              min-[1024px]:w-[300px]
              min-[1920px]:w-[450px]
              "
            >
              <label
                className="
                font-semibold
                text-third-blue
                mb-2 
                w-[200px]"
              >
                Fasilitas
              </label>
              <span
                className="
                max-[424px]:text-[10px] 
                text-zinc-600 
                w-[150px]
                min-[768px]:w-[300px]
                min-[1024px]:w-[500px]
                min-[1440px]:w-[600px]"
              >
                {room.fasilitas}
              </span>
            </div>
            <div
              className="
              grid 
              grid-cols-2 
              w-[220px]
              min-[1024px]:w-[300px]
              min-[1920px]:w-[450px]
              "
            >
              <label
                className="
                font-semibold
                text-third-blue
                mb-2 
                w-[200px]"
              >
                Harga
              </label>
              <span
                className="
                max-[424px]:text-[10px] 
                text-zinc-600 
                w-[150px]
                min-[768px]:w-[300px]
                min-[1024px]:w-[500px]
                min-[1440px]:w-[600px]"
              >
                {room.harga}
              </span>
            </div>
            <div
              className="
              grid 
              grid-cols-2 
              w-[220px]
              min-[1024px]:w-[300px]
              min-[1920px]:w-[450px]
              "
            >
              <label
                className="
                font-semibold
                text-third-blue
                mb-2 
                w-[200px]"
              >
                Status
              </label>
              <span
                className="
                max-[424px]:text-[10px] 
                text-zinc-600 
                w-[150px]
                min-[768px]:w-[300px]
                min-[1024px]:w-[500px]
                min-[1440px]:w-[600px]"
              >
                {room.status}
              </span>
            </div>
            <div
              className="
              grid 
              grid-cols-2 
              w-[220px]
              min-[1024px]:w-[300px]
              min-[1920px]:w-[450px]
              "
            >
              <label
                className="
                font-semibold
                text-third-blue
                mb-2 
                w-[200px]"
              >
                Keterangan
              </label>
              <span
                className="
                max-[424px]:text-[10px] 
              text-zinc-600 
              w-[150px]
              min-[768px]:w-[300px]
              min-[1024px]:w-[500px]
              min-[1440px]:w-[600px]
              min-[1920px]:w-[800px]"
              >
                {room.keterangan}
              </span>
            </div>
            <div
              className="
              grid 
              grid-cols-2 
              w-[220px]
              min-[1024px]:w-[300px]
              min-[1920px]:w-[450px]
              "
            >
              <label
                className="
                font-semibold
                text-third-blue
                mb-2 
                w-[200px]"
              >
                Image
              </label>
              <img src={room.image} />
            </div>
          </form>
        </div>
      </div>
    )
  );
}
